config/routes.rb
Rails.application.routes.draw do
  # ルーティングを登録するファイルです。 ルーティングというのは、ブラウザからRailsアプリへ渡される情報をもとに、登録された動きを行わせるための振り分け設定 

  # ルートページをhomeコントローラのtopアクションに設定
  root "home#top"

  # 静的ページのルート
  get 'static_pages/privacy_policy'
  get 'static_pages/terms_of_service'

  # Deviseユーザー認証関連のルート設定
  # devise_for :usersを通じてユーザーモデルに対する認証ルートを生成
  # controllers オプションを使用して、Deviseのデフォルトのコントローラをカスタムコントローラにオーバーライド。
  # これにより、デフォルトの動作をカスタマイズ。
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'}

  # 特定のユーザーを削除するためのルート
  # match 'users.:id' => 'registrations#destroy'：この部分はregistrations コントローラの destroy アクションにルーティングするための設定。
  # 'users.:id' は、URLにユーザーのIDを含めることを指定しており、このIDをパラメータとしてdestroyアクションに渡します。
  # :via => :delete：これはHTTPメソッドとしてDELETEを指定しています。DELETEメソッドは、RESTful API（分散型システムにおける複数のソフトウェアを連携させるのに適した設計原則の集合、考え方）においてリソースを削除するための標準的な方法。
  # :as => :destroy_user：これは名前付きルートを設定しており、このルートにdestroy_user_pathやdestroy_user_urlといったヘルパーメソッドでアクセスできるようにしています。
  # これにより、ビューやコントローラー内でこのルートを簡単に参照できます。
  match 'users.:id' => 'registrations#destroy', :via => :delete, :as => :destroy_user

  # ユーザー関連のルート、限定的なリソースのみ使用
  # ユーザーリソースの中でeditアクションとshowアクションに対するルートのみを生成する
  resources :users, only: [:edit, :show] do
    # memberブロック内では、特定のユーザーに関連する追加のアクションのルートを定義しています。
    member do
      # get :likes：各ユーザーの「いいね！」リストを表示するためのページへのルート
      get :likes
      # get :orders：ユーザーの注文履歴を表示するためのページへのルートです。
      get :orders
      # get :sales：ユーザーが行った販売の履歴を表示するためのページへのルートです。
      get :sales
    end
  end

  # サービスとレビュー関連のネストされたリソース
  # ユーザーはサービスに対してレビューを投稿したり、既存のレビューを編集することができます。
  # ネストされているため、URLはservices/:service_id/reviews/:idの形式で、サービスIDに基づいてレビューを管理することができます。
  resources :services do
    resources :reviews, only: [:new, :create, :edit, :update]

    # collection doブロック内のpost '/filter', to: 'services#filter'は、servicesリソースに対するカスタムのルートを定義しています。
    # このpostリクエストはservices#filterアクションにマッピングされ、これを使用してサービスを特定の基準でフィルタリングするフォームを処理します。
    collection do
      post '/filter', to: 'services#filter' # サービスをフィルターするアクション
    end
  end

  # いいね機能のルート
  resources :likes, only: [:create, :destroy]

  # 注文関連のルート
  resources :orders do
    # collection doブロック内のget :completedは、注文リソース全体に関連するカスタムアクションを定義
    # 完了した注文の一覧を表示するページに対するルートを提供
    # collectionキーワードは、このアクションが特定の注文のIDに依存しないことを意味する
    # つまり、このルートは/orders/completedの形でアクセスされ、すべての完了した注文を一覧表示するページへと導きます。
    collection do
      get :completed # 完了した注文の表示
    end
    # memberキーワードは、これらのアクションが特定の注文のIDに対して適用されることを意味する
    # URLはそれぞれ/orders/:id/acceptと/orders/:id/rejectの形になります
    # putメソッドは、注文の状態を変更するために使用され、これにより注文の状態が「承認された」または「拒否された」に更新されます。
    member do
      put :accept  # 注文の承認
      put :reject  # 注文の拒否
    end
  end
end

app/models/service.rb
# サービス情報を管理するモデルで、各サービスはタイトルと詳細を持ち、カテゴリー、ユーザー、レビュー、いいね、および注文と関連付けられています。
class Service < ApplicationRecord
  # 特定のキーワードに基づいてアクティブなサービスを検索するスコープです。
  # タイトルまたは詳細にキーワードが含まれるサービスを返します。
  # scope は、特定のクエリ条件に基づいてデータを取得する際に再利用可能なメソッドを作成するためのものです。
  # ここでの scope は by_keyword という名前で定義されており、これにより、モデルのどこからでも Model.by_keyword(some_keyword) の形で呼び出すことができます。
  # ここでは keyword をパラメータとして受け取り、このキーワードを使用して検索を行います。
  # activeは、アクティブな（例えば、削除されていないなどの条件を満たす）レコードのみを返すものです。
  # where クローズはSQLクエリを構築するために使用され、ここでは title または detail フィールドに keyword が含まれているレコードを検索します。
  # "title LIKE ? OR detail LIKE ?" はSQLのLIKE演算子を使った条件式で、指定されたキーワードがタイトルまたは詳細に部分一致するレコードを検索します。
  # "%#{keyword}%" は、キーワードを含む任意の文字列にマッチするためのワイルドカード（%）を含む検索パターンです。
  scope :by_keyword, ->(keyword) { active.where("title LIKE ? OR detail LIKE ?", "%#{keyword}%", "%#{keyword}%") }

  belongs_to :user
  has_many :orders
  belongs_to :category
  has_many :reviews
  # サービスには複数の「いいね」が関連付けられており、サービスが削除されると関連する「いいね」も削除されます。
  has_many :likes, dependent: :destroy
  # サービスには一つの画像が添付されています。これはユーザーがサービスを視覚的に識別するのに役立ちます。
  has_one_attached :image

  # タイトルは必須であり、最大100文字までです。100文字を超えるとエラーメッセージが表示されます。
  validates :title,
    presence: true,
    length: {
      maximum: 100,
      too_long: ':El nombre del servicio debe tener menos de %{count} caracteres.'
    }

  validates :detail, presence: true

  # 「deleted_at」がnilのサービスのみを返すスコープで、アクティブなサービスをフィルタリングします。
  scope :active, -> { where(deleted_at: nil) }

  # ソフトデリートを行い、サービスの「deleted_at」を現在時刻に設定します。これによりサービスは非アクティブになります。
  def soft_delete
    update_attribute(:deleted_at, Time.now)
  end

  # サービスに対するすべてのレビューの平均評価を計算し、小数点以下2桁で丸めて返します。
  # reviews はこのクラスに関連付けられた Review モデルのインスタンスのコレクションです。
  # この関連付けは、通常は has_many などのアソシエーションを通じて設定されます。
  #.average(:rating) は、reviews コレクションに含まれる rating 属性の平均値を計算するためのメソッドです。
  # これはSQLの AVG 関数を使用してデータベースレベルで計算され、効率的に動作します。
  # .average メソッドが返す値は通常 BigDecimal や nil です（特にレビューが存在しない場合）。
  # to_f はこの値を浮動小数点数に変換します。これにより、後続の数値操作が容易になります。
  # round(2) は、浮動小数点数を小数点以下2桁で丸めるためのメソッドです。これにより、表示や処理を行う際により扱いやすい形式になります。
  # :rating シンボルがデータベースのカラム名
  def average_rating
    reviews.average(:rating).to_f.round(2)
  end

  # サービスが受けた「いいね」の総数を返します。
  # length メソッドは、likes コレクションに含まれる要素の数を返します。これはリスト内のアイテムの総数を直接カウントするためのRubyの配列メソッドです。
  #def count_likes
  #  likes.length
  #end

  # サービスが削除されたかどうかを確認します。
  # deleted? メソッドは、データベースから実際にレコードを削除することなく、削除されたとマークすることができます。これにより、データの整合性を維持し、データの復旧が可能になります。
  # .present? メソッドは、deleted_at カラムに値が設定されているかどうかをチェックします。
  def deleted?
    deleted_at.present?
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # ユーザー認証を除く、index, show, filterアクションで行う
  before_action :authenticate_user, except: [:index, :show, :filter]
  # 特定のアクションでサービスを設定
  # only: %i[edit update destroy]: このオプションは、before_actionが適用されるアクションを限定します。ここでは、:edit、:update、:destroy の各アクションが実行される前にset_serviceメソッドが呼び出されます。この指定により、他のアクションではset_serviceメソッドは実行されません。
  # 通常、set_serviceメソッドは指定されたIDに基づいてServiceオブジェクトをデータベースから取得し、それをインスタンス変数（例えば@service）に格納することで、edit、update、destroyアクションが利用できるようにします。
  before_action :set_service, only: %i[edit update destroy]

  # サービスの一覧表示
  def index
    # Active Recordの`preload`メソッドを使ってN+1問題を解決しつつ、アクティブなサービスを降順にページネーションで表示
    #元々preload(:user)だったものをpreload(:reviews)に変更済み
    #serviceの配列からreviewを取るコードになっているので、以下のように実装するとN+1を回避できる
    #https://zenn.dev/gottsu/articles/914d45332450a3
    #https://github.com/taishoiwamoto/Olumeca/blob/85e8220a2683d08699ab638fffef6e72be620079/app/views/services/_services.html.erb#L16
    # 確認方法：rails sでサーバーを起動したとき、そのコンソールに色々と文字が出力される。ここはサーバーの稼働ログが出力される場所で、そこにSQLのログも出力されます。それを見て、N+1が修正されたかどうかが判断できる
    # page(params[:page]) はページネーションのためのメソッドで、通常は kaminari や will_paginate のようなページネーションライブラリによって提供されます。これにより、大量のレコードを扱う際にユーザーインターフェースが過負荷になることを防ぎます。params[:page] は現在のページ番号を指定し、これに基づいて表示するレコードの範囲が決まります。
    @services = Service.active.preload(:reviews).order(created_at: :desc).page(params[:page]).per(30)
  end

  # サービスの詳細表示
  def show
    # 特定のサービスを取得し、関連するユーザーとレビューも事前に読み込む
    # preload(:user)があることで処理速度の改善を確認
    @service = Service.active.preload(:user).find(params[:id])
    @user = @service.user
    @user_has_liked = Like.user_and_service(current_user.id, @service.id) if current_user
    # preload(:user)によりUser Loadの削減を確認
    @reviews = @service.reviews.preload(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  # 新規サービス作成ページ
  def new
    @service = Service.new
  end

  # サービスの新規作成
  def create
    # build メソッドは、新しい Service オブジェクトをメモリ上に作成しますが、この時点ではデータベースには保存されません。build は新しいレコードをインスタンス化するために使われ、特に関連付けられたオブジェクトのコレクションに新しいオブジェクトを追加する際に便利です。
    # service_params は、通常コントローラ内で定義されるプライベートメソッドです。このメソッドはストロングパラメータを使用しており、フォームから送信されたデータから安全にパラメータを取り出すために使用されます。具体的には、許可されたパラメータ（例：サービス名、説明など）のみを含むハッシュを返します。
    @service = current_user.services.build service_params

    if @service.save
      redirect_to service_path(@service), notice: "Has creado un servicio"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # サービスの編集ページ
  def edit; end

  # サービスの更新
  def update
    # service_params は、通常コントローラ内で定義されるプライベートメソッドです。このメソッドはストロングパラメータを使用しており、フォームから送信されたデータから安全にパラメータを取り出すために使用されます。具体的には、許可されたパラメータ（例：サービス名、説明など）のみを含むハッシュを返します。
    if @service.update service_params
      redirect_to service_path(@service), notice: 'Has editado un servicio'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  # サービスの論理削除
  def destroy
    @service.soft_delete

    redirect_to user_path(current_user), notice: 'Has eliminado un servicio'
  end

  # サービスのフィルタリング
  def filter
    @services = Service.all

    # カテゴリによる絞り込み
    #未対応 [重要度: 低] Serviceテーブルのデータ量が多くなった際に時間がかかる可能性が高いです。LIKE検索の有効的な軽量化方法は難しいため、外部の検索サービスなどの利用をお勧めします。service.rbの二行目の箇所。規模がかなり大きくなる前に対策をした方が良い程度。サービステーブルが万くらいまでは気にしなくても良さそう。
    if params[:category_id].present?
      @services = @services.where(category_id: params[:category_id])
    end

    # キーワードによる絞り込み
    if params[:keyword].present?
      @services = @services.by_keyword(params[:keyword])
    end

    # ユーザーの事前読み込みとアクティブなサービスの降順にページネーションで表示
    # preload(:user)によりUser Loadの読み込み回数削減を確認
    @services = @services.preload(:user).active.order(created_at: :desc).page(params[:page]).per(30)

    # ページ全体をリロードすることなく、ページの一部分だけをサーバーからの新しい情報で更新するために使われます。 
    # respond_to ブロックを使用して、異なるフォーマットに応じた応答を設定します。
    # respond_to do |format| の箇所は、Ruby on Railsにおいて、クライアントからのリクエストに応じて異なるフォーマットでレスポンスを返すためのメソッドを設定する場所です。
    # このブロックを使用することで、同一のアクション（この場合は filter アクション）において、リクエストされたフォーマットに応じた適切な処理を行い、それぞれ異なるフォーマットでデータを返すことができます。
    respond_to do |format|
      # format.turbo_stream ブロックを使用して、Turbo Stream形式での応答を定義します。
      format.turbo_stream { 
        # render メソッドを使用して、指定された部分テンプレートをレンダリングし、
        # turbo_stream.replace を使って特定のHTML要素('services')を置換します。
        # 'services/services'は_services.html.erb（または同様のテンプレートエンジンを使用している場合は違う拡張子）というファイルを指す。
        render turbo_stream: turbo_stream.replace(
          'services', # これは置換されるHTML要素のIDです。このIDを持つHTML要素が新しい内容で更新されます。
          partial: 'services/services', # 置換に使用される部分テンプレートのパスです。部分テンプレートとは、再利用可能なビューの断片を意味します。
          locals: { services: @services } # これは、部分テンプレートに渡すローカル変数を定義しています。ここでは@servicesというインスタンス変数がテンプレート内で使用されます。
          )
        }
    end
  end


  private

  # サービスのパラメータ
  def service_params
    params.require(:service).permit(:title, :detail, :category_id, :image)
  end

  # 編集・更新・削除用にサービスを設定
  # 特定の Service オブジェクトをロードし、アクセス制御を行うために使用されるメソッドです。
  def set_service
    # user オブジェクトを直接比較する場合、事前にユーザー情報を読み込んでおくことで処理速度が向上します。
    @service = Service.preload(:user).find(params[:id])

    # この条件文は、@service の関連付けられた user が現在ログインしているユーザー (current_user) と同一であるかを確認します。
    # .eql? メソッドは、指定されたユーザーが現在のユーザーと「等しいか」を評価します。ここでの等価はオブジェクトのIDや値が一致することを意味します。
    unless @service.user.eql? current_user
      # and return は、リダイレクト後にさらなる処理を防ぐために使用され、リダイレクトが確実に完了することを保証します。
      redirect_to service_path(@service), notice: 'No tienes autorización' and return
    end
  end
end

app/helpers/services_helper.rb
# ServicesHelperモジュール: サービス関連のビューヘルパー関数を提供
module ServicesHelper
  # 与えられた評価を星のアイコンで表現するためのメソッド
  # @param rating [Integer, Float] 評価スコア（通常1から5の範囲）
  # @return [String] 評価スコアに対応する星のアイコン文字列
  # def render_stars(rating)
    # ratingを四捨五入し、その数だけ星のアイコンを連結して生成
  #  "⭐️" * rating.round
  #end
end

app/views/services/_form.html.erb
<div class="main">
  <div class="form-container">
    <h1 class="ms-2 me-2">Publicar</h1>
    <div class="form">
      <div class="form-body">
        <!-- Railsのform_withヘルパーを使ってサービスモデルに基づくフォームを作成 -->
        <%= form_with(model: service, local: true, html: { class: 'needs-validation' }) do |f| %>
          <!-- タイトルに関連するエラーメッセージを表示 -->
          <% @service.errors.full_messages_for(:title).each do |message| %>
            <div class="alert alert-danger">
              <%= message %>
            </div>
          <% end %>
          <!-- 詳細に関連するエラーメッセージを表示 -->
          <% @service.errors.full_messages_for(:detail).each do |message| %>
            <div class="alert alert-danger">
              <%= message %>
            </div>
          <% end %>
          <!-- タイトル入力フィールド -->
          <div class="mb-3">
            <%= f.label :title, 'Título', class: 'form-label' %>
            <%= f.text_field :title, value: @service.title, class: 'form-control', required: true %>
            <div class="invalid-feedback">Por favor, ingresa un título.</div>
          </div>
          <!-- 画像ファイル入力フィールド -->
          <div class="mb-3">
            <%= f.label :image, 'Imagen', class: 'form-label' %>
            <% if @service.image.attached? %>
              <%= f.file_field :image, class: 'form-control' %>
            <% else %>
              <%= f.file_field :image, class: 'form-control', required: true %>
              <div class="invalid-feedback">Por favor, selecciona una imagen.</div>
            <% end %>
          </div>
          <!-- カテゴリ選択ドロップダウン -->
          <div class="mb-3">
            <%= f.label :category_id, class: 'form-label' %>
            <%# カテゴリの選択フィールドを生成します。選択オプションはCategoryモデルから取得し、現在のサービスのカテゴリIDをデフォルト値として設定します。%>
            <%# required: @service.category_id.nil?: @serviceのcategory_idが未設定（nil）の場合に、フォームの入力フィールドを必須（入力が必要）とするかどうかを動的に設定するために使用されます。これにより、ユーザーがフォームを送信する際に、カテゴリーIDがまだ選択されていない場合には値を入力しなければならないという要求がブラウザに伝えられます。%>
            <%= f.select :category_id, options_for_select(Category.all.map{|category| [category.name, category.id]}, @service.category_id), { include_blank: 'Por favor, elija de la siguiente lista' }, { class: 'form-select', required: @service.category_id.nil? } %>
            <div class="invalid-feedback">Por favor, selecciona una categoría.</div>
          </div>
          <!-- 詳細テキストエリア -->
          <div class="mb-3">
            <%= f.label :detail, 'Detalle', class: 'form-label' %>
            <%# サービスの詳細を入力するためのテキストエリアをフォームに生成します。 %>
            <%= f.text_area :detail, value: @service.detail, class: 'form-control', required: true, rows: 5 %>
            <div class="invalid-feedback">Por favor, proporciona un detalle.</div>
          </div>
          <!-- 提出ボタン -->
          <div class="d-grid gap-2 col-6">
            <%= f.submit text_btn, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<!-- 
renderメソッドを使用して、_form.html.erbという名前の部分テンプレート（パーシャル）をレンダリングするためのものです。
このパーシャルには、serviceオブジェクトとtext_btnというテキストを含むボタンラベルを引数として渡しています。

render 'form': これは、formという名前のパーシャルビューを呼び出します。
通常、このパーシャルは同じフォルダ内か、Railsのビューのpartialsフォルダ内に_form.html.erbとして存在します。
アンダースコア(_)は、ファイルがパーシャルであることを示しますが、renderメソッドを使用する際にはそのアンダースコアを省略します。

{ service: @service, text_btn: 'Actualizar' }: これは、パーシャルに渡すローカル変数のハッシュです。

service: @serviceは、このフォームが編集する特定のserviceオブジェクトをパーシャルに渡します。この変数を使って、フォームフィールドの初期値を設定したり、特定のサービスの属性を表示したりします。
text_btn: 'Actualizar'は、フォームの送信ボタンに「Actualizar」（更新）と表示するためのテキストを指定しています。これにより、同じフォームパーシャルを新規作成と更新の両方のコンテキストで再利用できるようになります。 
-->


<%= render 'form', { service: @service, text_btn: 'Actualizar' } %>

app/views/services/show.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <!-- サービス情報の主要な表示部分 -->
      <div class="col-lg-7 col-md-8 col-12 order-1 order-md-1 mt-5">
        <div class="service-show-item">
          <!-- 編集・削除ボタン -->
          <div class="flex-end">
            <% if current_user && @service.user_id == current_user.id %>
              <!-- 編集ボタン -->
              <!-- GET メソッド　編集フォームをユーザーに表示するため -->
              <%= button_to edit_service_path(@service), method: :get, class: "btn btn-primary btn-sm me-2" do %>
                <i class="fa-solid fa-pen-to-square"></i> Editar
              <% end %>
              <!-- 削除ボタン -->
              <%= button_to service_path(@service), method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro de que deseas eliminar este servicio?" }} do %>
                <i class="fa-solid fa-trash"></i> Eliminar
              <% end %>
            <% end %>
          </div>
          <!-- サービスタイトル -->
          <h1 class="main-title mt-3"><%= @service.title %></h1>
          <!-- 評価といいねボタン -->
          <div class="flex-space-between">
            <div class="star">
              <% if @reviews.present? %>
                <div class="average-rating">
                  <p><%= "⭐️" %> <%= sprintf('%.2f', @service.average_rating) %></p>
                </div>
              <% else %>
                --
              <% end %>
            </div>
            <!-- いいねボタン -->
            <div class="like-button">
              <% if current_user %>
                <% if @user_has_liked %>
                  <!-- ハッシュ -->
                  <%= button_to like_path(service_id: @service.id), method: :delete do %>
                    <span class="fa fa-heart liked-btn"></span>
                  <% end %>
                <% else %>
                  <!-- ハッシュ -->
                  <%= button_to likes_path(service_id: @service.id), method: :post do %>
                    <span class="fa fa-heart unliked-btn"></span>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
          <!-- カテゴリ表示 -->
          <!-- @service.category&.name: ここでは、@service インスタンスの category という関連オブジェクトの name 属性にアクセスしています。&. はセーフナビゲーション演算子と呼ばれ、category が nil である場合に NoMethodError を防ぐために使われます。つまり、category が存在しない場合には、name メソッドを呼び出すことなく nil を返します。 -->
          <!-- || "": これは、左辺の式が nil または false を返した場合に右辺の値（この場合は空文字列 ""）を返すOR演算子です。つまり、@service.category が nil または @service.category.name が nil の場合には、空文字列を出力します。 -->
          <div class="mb-1"><%= @service.category&.name || "" %></div>
          <!-- サービス画像 -->
          <div class="service-image">
            <% if @service.image.attached? %>
              <%= image_tag(@service.image, class: "service-image") %>
            <% else %>
              <%= image_tag('default_service.jpg', class: "service-image") %>
            <% end %>
          </div>
          <!-- サービス詳細説明 -->
          <!-- h(@service.detail): h は HTML エスケープヘルパーです。これは、@service.detail に含まれる文字列を安全にHTMLに表示するために使われます。つまり、HTMLに影響を与える可能性のある文字（例えば <, >, & など）をエスケープし、安全な文字列としてブラウザに表示するための処理を行います。これにより、クロスサイトスクリプティング（XSS）攻撃などのセキュリティリスクを防ぎます。 -->
          <!-- simple_format(text): このヘルパーメソッドは、テキストをより読みやすい形式のHTMLに変換します。具体的には、改行文字（\n）を <br> タグに変換し、段落として整形するためにテキストを <p> タグで囲みます。simple_format は引数として渡されたテキストを受け取り、改行ごとに段落を作成します。 -->
          <p><%= simple_format(h(@service.detail)) %></p>
        </div>
        <!-- サービス注文リンク -->
        <div class="d-grid gap-2 col-10 mx-auto">
          <%= link_to "Hacer el pedido", new_order_path(seller_id: @service.user_id, service_id: @service.id, buyer_id: current_user&.id), class: "btn btn-primary btn-lg" %>
        </div>
        <!-- サービス評価タイトル -->
        <h2 class="sub-title mt-5 mb-4">Evaluación</h2>
        <!-- サービス評価表示 -->
        <% if @reviews.any? %>
          <div class="row">
            <% @reviews.each do |review| %>
              <div class="col-12 mb-4">
                <div class="card full-width">
                  <div class="card-body">
                    <div class="flex-grow-1">
                      <div class="d-flex align-items-center mt-2">
                        <!-- レビュー投稿者の画像 -->
                        <% if review.user.deleted? %>
                          <%= image_tag('default_user.jpg', class: "rounded-circle mr-3 small-image") %>
                        <% elsif review.user.image.attached? %>
                          <%= image_tag(review.user.image, class: "rounded-circle mr-3 small-image") %>
                        <% else %>
                          <%= image_tag('default_user.jpg', class: "rounded-circle mr-3 small-image") %>
                        <% end %>
                        <!-- レビュー評価 -->
                        <% if review.rating.present? %>
                          <div class="ms-2"><%= "⭐️" * review.rating %></div>
                        <% end %>
                      </div>
                      <!-- レビュー投稿者名 -->
                      <% if review.user.deleted? %>
                        <p class="font-weight-bold mt-2 mb-0">Comprador/a: Dado de baja</p>
                      <% else %>
                        <p class="font-weight-bold mt-2 mb-0">Comprador/a: <%= review.user.name %></p>
                      <% end %>
                      <!-- レビュー投稿日時 -->
                      <div class="d-flex justify-content-start mt-2 small-text">
                        <div class="me-2">Creación: <%= review.created_at.strftime("%d/%m/%Y %H:%M") %></div>
                        <div class>Actualización: <%= review.updated_at.strftime("%d/%m/%Y %H:%M") %></div>
                      </div>
                      <!-- レビューコメント -->
                      <!-- h(review.comment): h は HTML エスケープヘルパーです。これは、@review.comment に含まれる文字列を安全にHTMLに表示するために使われます。つまり、HTMLに影響を与える可能性のある文字（例えば <, >, & など）をエスケープし、安全な文字列としてブラウザに表示するための処理を行います。これにより、クロスサイトスクリプティング（XSS）攻撃などのセキュリティリスクを防ぎます。 -->
                      <p><%= simple_format(h(review.comment)) %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <!-- レビューページネーション -->
          <%= paginate @reviews %>
        <% else %>
          <p>No hay evaluaciones.</p>
        <% end %>
      </div>
      <!-- サービス提供者のプロフィールカード -->
      <div class="col-lg-3 col-md-4 col-12 order-2 order-md-1 mb-5 mt-5">
        <%= link_to user_path(@service.user), class: 'text-decoration-none text-dark' do %>
          <div class="card">
            <div class="card-body text-center">
              <% if @service.user.image.attached? %>
                <%= image_tag(@service.user.image, class: 'rounded-circle mx-auto d-block mediam-image-container') %>
              <% else %>
                <%= image_tag('default_user.jpg', class: 'rounded-circle mx-auto d-block mediam-image-container') %>
              <% end %>
              <!-- サービス提供者名と評価 -->
              <p class="card-title mt-3 mb-1"><%= @service.user.name %></p>
              <% if @service.average_rating > 0 %>
                <p class="mb-0"><%= "⭐️" %> <%= sprintf('%.2f', @service.average_rating) %></p>
              <% else %>
                <p class="mb-0"> -- </p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>