config/routes.rb
Rails.application.routes.draw do
  # ルーティングを登録するファイルです。 ルーティングというのは、ブラウザからRailsアプリへ渡される情報をもとに、登録された動きを行わせるための振り分け設定 

  # ルートページをhomeコントローラのtopアクションに設定
  root "home#top"

  # 静的ページのルート
  get 'static_pages/privacy_policy'
  get 'static_pages/terms_of_service'

  # Deviseユーザー認証関連のルート設定
  # devise_for :usersを通じてユーザーモデルに対する認証ルートを生成
  # controllers オプションを使用して、Deviseのデフォルトのコントローラをカスタムコントローラにオーバーライド。
  # これにより、デフォルトの動作をカスタマイズ。
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'}

  # 特定のユーザーを削除するためのルート
  # match 'users.:id' => 'registrations#destroy'：この部分はregistrations コントローラの destroy アクションにルーティングするための設定。
  # 'users.:id' は、URLにユーザーのIDを含めることを指定しており、このIDをパラメータとしてdestroyアクションに渡します。
  # :via => :delete：これはHTTPメソッドとしてDELETEを指定しています。DELETEメソッドは、RESTful API（分散型システムにおける複数のソフトウェアを連携させるのに適した設計原則の集合、考え方）においてリソースを削除するための標準的な方法。
  # :as => :destroy_user：これは名前付きルートを設定しており、このルートにdestroy_user_pathやdestroy_user_urlといったヘルパーメソッドでアクセスできるようにしています。
  # これにより、ビューやコントローラー内でこのルートを簡単に参照できます。
  match 'users.:id' => 'registrations#destroy', :via => :delete, :as => :destroy_user

  # ユーザー関連のルート、限定的なリソースのみ使用
  # ユーザーリソースの中でeditアクションとshowアクションに対するルートのみを生成する
  resources :users, only: [:edit, :show] do
    # memberブロック内では、特定のユーザーに関連する追加のアクションのルートを定義しています。
    member do
      # get :likes：各ユーザーの「いいね！」リストを表示するためのページへのルート
      get :likes
      # get :orders：ユーザーの注文履歴を表示するためのページへのルートです。
      get :orders
      # get :sales：ユーザーが行った販売の履歴を表示するためのページへのルートです。
      get :sales
    end
  end

  # サービスとレビュー関連のネストされたリソース
  # ユーザーはサービスに対してレビューを投稿したり、既存のレビューを編集することができます。
  # ネストされているため、URLはservices/:service_id/reviews/:idの形式で、サービスIDに基づいてレビューを管理することができます。
  resources :services do
    resources :reviews, only: [:new, :create, :edit, :update]

    # collection doブロック内のpost '/filter', to: 'services#filter'は、servicesリソースに対するカスタムのルートを定義しています。
    # このpostリクエストはservices#filterアクションにマッピングされ、これを使用してサービスを特定の基準でフィルタリングするフォームを処理します。
    collection do
      post '/filter', to: 'services#filter' # サービスをフィルターするアクション
    end
  end

  # いいね機能のルート
  resources :likes, only: [:create, :destroy]

  # 注文関連のルート
  resources :orders do
    # collection doブロック内のget :completedは、注文リソース全体に関連するカスタムアクションを定義
    # 完了した注文の一覧を表示するページに対するルートを提供
    # collectionキーワードは、このアクションが特定の注文のIDに依存しないことを意味する
    # つまり、このルートは/orders/completedの形でアクセスされ、すべての完了した注文を一覧表示するページへと導きます。
    collection do
      get :completed # 完了した注文の表示
    end
    # memberキーワードは、これらのアクションが特定の注文のIDに対して適用されることを意味する
    # URLはそれぞれ/orders/:id/acceptと/orders/:id/rejectの形になります
    # putメソッドは、注文の状態を変更するために使用され、これにより注文の状態が「承認された」または「拒否された」に更新されます。
    member do
      put :accept  # 注文の承認
      put :reject  # 注文の拒否
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # 新規登録時に特定のパラメータを許可するための設定
  before_action :configure_sign_up_params, only: [:create]
  # アカウント更新時に特定のパラメータを許可するための設定
  before_action :configure_account_update_params, only: [:update]
  # 新規登録時にメールアドレスの重複チェックを行う
  before_action :check_email_uniqueness, only: [:create]

  # DELETE /resource
  # ユーザーのアカウントを論理削除し、セッションを終了させる
  def destroy
    resource.soft_delete

    sign_out resource
    redirect_to root_path, notice: 'La cuenta de usuario fue cancelada'
  end

  # protected キーワードによって定義されたメソッドは、同じクラスまたはそのサブクラスのインスタンスからのみアクセス可能です。
  # これは、クラス外部からは直接呼び出すことができないことを意味します。
  protected

  # アカウント更新後のリダイレクト先
  def after_update_path_for(resource)
    user_path(current_user)
  end

  # サインアップ時に追加で許可するパラメータを設定
  #def configure_sign_up_params
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :image])
  #end

  # アカウント更新時に追加で許可するパラメータを設定
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :image])
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   redirect_to root
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # 許可する追加のパラメータがある場合は、サニタイザーに追加する。
  def configure_sign_up_params
    # :sign_up は、Devise で使用されるアクション
    devise_parameter_sanitizer.permit(:sign_up, keys: [:agreement, :name, :phone_number, :email, :password, :password_confirmation])
  end

  # メールアドレスの重複チェックを行うメソッド
  def check_email_uniqueness
    if User.email_taken?(params[:user][:email])
      existing_user = User.find_by(email: params[:user][:email])
      if existing_user.deleted_at.nil?
        # Email is in use by an active account
        # アクティブなアカウントでメールアドレスが使用されている場合
        flash[:error] = "This email is already registered. If you forgot your password, you can reset it."
      else
        # Email is in use by an inactive account, allow the registration.
        # 非アクティブなアカウントでメールアドレスが使用されている場合、登録を許可
        bypass_sign_in(existing_user) # Deviseのサインインをバイパス
        existing_user.update(deleted_at: nil) # 既存のユーザーをアクティブにする
        redirect_to new_user_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # サインイン作成時のアクションをオーバーライド
  def create
    if verify_recaptcha
      #redirect_to root_path
      # reCAPTCHA認証が成功した場合、Deviseのデフォルトのサインイン処理を実行
      super
      #render :edit
    else
      # reCAPTCHA認証が失敗した場合、サインインページにリダイレクトしエラーメッセージを表示
      self.resource = resource_class.new(sign_in_params)
      flash.now[:alert] = 'Recaptcha verification failed'
      render :new
    end
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザー認証を除く、showアクションで行う
  before_action :authenticate_user, except: [:show]
  # show, likes, orders, salesアクションでアクティブなユーザーを設定
  before_action :find_active_user, only: %i[show likes orders sales]

  # ユーザーの詳細ページ
  def show
    # ユーザーのアクティブなサービスを降順に表示
    @services = @user.services.active.order(created_at: :desc)
    # ユーザーの平均評価
    @average_rating = @user.average_service_rating

    # 表示するサービスIDを取得
    # .pluck(:id) を使用して、そのコレクション内の全サービスオブジェクトから id 属性のみを抽出し、配列として service_ids に格納しています。
    # .pluck メソッドは、指定されたカラムの値だけを直接データベースから取り出すので、メモリ使用量と処理時間の節約に効果的です。
    # 直接的なIN句でIDを指定しているため、データベースがより効率的にデータをフィルタリングし、取得することができるからです。
    service_ids = @services.pluck(:id)
    # 関連するレビューを取得し、ページネーションで表示
    # includes(:service, :user) がある場合: 最初のクエリで必要な Review, Service, User のデータを全て取得します。これにより、レビューを表示する際にそれぞれの Service と User を即座に参照できます。
    # includes(:service, :user) がない場合: Review をロードした後、それぞれの Review について、関連する Service と User を個別にクエリします。これは多くの追加クエリを引き起こし、パフォーマンスが低下する原因となります。
    @reviews = Review.includes(:service, :user).where(service_id: service_ids).order(created_at: :desc).page(params[:page]).per(10)
  end

  # ユーザーが「いいね」したサービス一覧
  def likes
    # 「いいね」したサービスを取得し、ページネーションで表示
    # 各サービスに紐付けられたユーザー情報をあらかじめ読み込む（プリロードする）ことで、サービスに紐付くユーザー情報を表示する際に発生する追加のクエリ（N+1クエリ問題）を防ぎます。
    # where(likes: { user_id: current_user.id }):で、likes テーブルにある user_id カラムが現在ログインしているユーザー（current_user.id）と一致するレコードのみをフィルタリングします。これにより、現在のユーザーが「いいね」したサービスのみが取得されます。
    # .page(params[:page])で、pageはメソッド、params[:page]は辞書。
    @services = Service.joins(:likes).preload(:user).where(likes: { user_id: current_user.id }).where(deleted_at: nil).order("likes.created_at desc").page(params[:page]).per(30)
  end

  # ユーザーの注文一覧
  def orders
    # ユーザーの注文を取得し、ページネーションで表示
    # 注文に関連する seller（販売者）と、service（サービス）およびそのサービスに紐づく user（サービス提供者）の情報をプリロードします。これにより、注文に関連するデータを表示する際に発生する追加のクエリ（N+1クエリ問題）を防ぎます。
    @orders = Order.where(buyer_id: current_user.id).includes(:seller, service: :user).order(created_at: :desc).page(params[:page]).per(30)

    # 注文に関連するサービスIDを取得
    # 特定の @orders コレクション（Order オブジェクトの配列）から各注文に関連付けられている service_id を取得し、それらの ID を配列として service_ids に格納
    # mapメソッドは、コレクション（例えば配列や範囲）の各要素に対してブロック内の処理を適用し、結果を新しい配列として返します。
    # :service_id: service_id はシンボルで、これは Order オブジェクトの service_id 属性（メソッド）を指します。
    service_ids = @orders.map(&:service_id)
    # ユーザーが投稿したレビューを取得
    @reviews_by_user = Review.where(user_id: current_user.id, service_id: service_ids)
  end

  # ユーザーの売上一覧
  def sales
    # ユーザーの売上を取得し、ページネーションで表示
    @sales = Order.where(seller_id: current_user.id).includes(:buyer, service: :user).order(created_at: :desc).page(params[:page]).per(30)
  end

  # ユーザーのアカウント削除
  def destroy
    if current_user.soft_delete
      redirect_to root_path, notice: 'Has eliminado tu cuenta.'
    else
      redirect_to user_path(current_user), alert: 'No se pudo eliminar tu cuenta.'
    end
  end

  private

  # アクティブなユーザーを設定
  def find_active_user
    @user = User.active.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/likes.html.erb
<div class="main">
  <div class="container">
    <!-- ページのタイトルを中央揃えで表示 -->
    <h1 class="text-center">Favoritos</h1>
    <div class="cards-container">
     <!-- お気に入りサービスがあるかどうかを確認 -->
      <% if @services.any? %>
        <!-- お気に入りサービスを一つずつ表示 -->
        <% @services.each do |service| %>
          <!-- サービス詳細ページへのリンク -->
          <%= link_to service_path(service.id) do %>
            <div class="card">
              <!-- サービス画像が添付されているかどうかを確認し、添付されていればその画像を表示 -->
              <% if service.image.attached? %>
                <%= image_tag(service.image, class: "card-img-top", alt: "...") %>
              <% else %>
                <!-- 画像が添付されていなければデフォルト画像を表示 -->
                <%= image_tag('default_service.jpg', class: "card-img-top", alt: "...") %>
              <% end %>
              <div class="card-body">
                <!-- サービスのタイトルを表示（30文字に省略） -->
                <p class="card-title"><%= service.title.truncate(30) %></p>
                <!-- サービス提供者の名前を表示 -->
                <p class="card-text"><%= service.user.name %></p>
                <!-- レビューがあれば平均評価を星と数値で表示 -->
                <div class="star">
                  <% reviews = service.reviews %>
                  <% if reviews.present? %>
                    <% average_rating = service.average_rating %>
                    <%= "⭐️" %> <%= sprintf('%.2f', average_rating) %>
                  <% else %>
                    <!-- レビューがなければ評価なしと表示 -->
                    --
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <!-- お気に入りサービスのページネーションを表示 -->
        <%= paginate @services %>
      <% else %>
        <!-- お気に入りサービスがない場合のメッセージ -->
        <p>No tienes servicios favoritos.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/orders.html.erb
<div class="main">
  <div class="table-container">
    <!-- ページのタイトル -->
    <h1>Pedidos realizados</h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <!-- テーブルのヘッダー -->
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Estado</th>
            <th scope="col">Evaluación</th>
            <th scope="col">Info</th>
            <th scope="col">Vendedor/a</th>
            <th scope="col">Servicio</th>
          </tr>
        </thead>
        <!-- テーブルのボディ -->
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <!-- 注文日 -->
              <td><%= order.created_at.strftime("%d/%m/%Y") %></td>
              <!-- 注文の状態 -->
              <td>
                <% case order.status %>
                <% when 'pending' %>
                <%= button_tag get_order_status(order.status), class: "btn btn-secondary btn-sm", disabled: true %>
                <% when 'accepted' %>
                <%= button_tag get_order_status(order.status), class: "btn btn-success btn-sm", disabled: true %>
                <% when 'rejected' %>
                <%= button_tag get_order_status(order.status), class: "btn btn-danger btn-sm", disabled: true %>
              <% end %>
            </td>
            <!-- 評価リンク -->
            <td>
              <% if order.seller.deleted? %>
                N/A
              <% elsif order.accepted? %>
                <!-- この行では、インスタンス変数 @reviews_by_userから特定のサービスIDに一致するレビューを検索します。 -->
                <!-- find メソッドは最初に条件に一致する要素を返します。この場合、order.service_id と一致する service_id を持つレビューを探します。 -->
                <!-- 、|review|はブロック変数として機能し、@reviews_by_userの各要素（各レビュー）を順番にreviewという名前で参照できるようにします。ブロック内のコードはこの変数を使用して条件を評価し、条件に一致する最初の要素を見つけた場合にはその要素を返し、一致するものがない場合はnilを返します。 -->
                <% review_for_order = @reviews_by_user.find { |review| review.service_id == order.service_id } %>
                <% if review_for_order %>
                  <!-- review_for_order 変数が nil ではない場合（つまり、一致するレビューが見つかった場合）、そのレビューを編集するためのリンクを表示します。 -->
                  <%= link_to "Editar", edit_service_review_path(order.service, review_for_order), class: "btn btn-primary btn-sm"  %>
                <% else %>
                  <%= link_to "Evaluar", new_service_review_path(order.service), class: "btn btn-primary btn-sm" %>
                <% end %>
              <% end %>
            </td>
            <!-- 追加情報 -->
            <td>
              <% if order.seller.deleted? || order.pending? || order.rejected? %>
                N/A
              <% elsif order.accepted? %>
                <div class="info-item">
                  <i class="fa-solid fa-envelope"></i>: <%= order.seller.email %>
                </div>
                <div class="info-item">
                  <i class="fa-solid fa-phone"></i>: <%= order.seller.phone_number %>
                </div>
              <% end %>
            </td>
            <!-- 販売者情報 -->
            <td>
              <% if order.service.user.deleted? %>
                Dado de baja
              <% else %>
                <%= link_to order.service.user.name, user_path(order.seller), class: "link-text" %>
              <% end %>
            </td>
            <!-- サービス名 -->
            <td>
              <% if order.service.user.deleted? || order.service.deleted? %>
                Eliminado
              <% else %>
                <%= link_to order.service.title, service_path(order.service), class: "link-text" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- ページネーション -->
  <%= paginate @orders %>
</div>
</div>

app/views/users/sales.html.erb
<div class="main">
  <div class="table-container">
    <!-- サービス名 -->
    <h1>Pedidos recibidos</h1>
    <div class="table-responsive">
      <!-- テーブルの形式で注文情報を表示 -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Estado</th>
            <th scope="col">Acción</th>
            <th scope="col">Info</th>
            <th scope="col">Comprador/a</th>
            <th scope="col">Servicio</th>
          </tr>
        </thead>
        <tbody>
          <% @sales.each do |sale| %>
            <tr>
              <!-- 注文の作成日 -->
              <td><%= sale.created_at.strftime("%d/%m/%Y") %></td>
              <!-- 注文の現在の状態を表示、色分けされたボタンで状態を示す -->
              <td>
                <% case sale.status %>
                <% when 'pending' %>
                <%= button_tag get_order_status(sale.status), class: "btn btn-secondary btn-sm", disabled: true %>
                <% when 'accepted' %>
                <%= button_tag get_order_status(sale.status), class: "btn btn-success btn-sm", disabled: true %>
                <% when 'rejected' %>
                <%= button_tag get_order_status(sale.status), class: "btn btn-danger btn-sm", disabled: true %>
              <% end %>
            </td>
            <!-- 受け取った注文に対する行動オプション -->
            <td>
              <% if sale.buyer.deleted? || sale.accepted? || sale.rejected? %>
                N/A
              <% elsif sale.pending? %>
                <!-- 注文を承認または拒否するアクションボタン -->
                <div class="flex-container">
                  <%= button_to "Aceptar", accept_order_path(sale), method: :put, class: "btn btn-primary btn-sm me-2" %>
                  <%= button_to "Rechazar", reject_order_path(sale), method: :put, class: "btn btn-danger btn-sm" %>
                </div>
              <% end %>
            </td>
            <!-- 購入者の連絡情報 -->
            <td>
              <% if sale.buyer.deleted? || sale.pending? || sale.rejected? %>
                N/A
              <% elsif sale.accepted? %>
                <div class="info-item">
                  <i class="fa-solid fa-envelope"></i>: <%= sale.buyer.email %>
                </div>
                <div class="info-item">
                  <i class="fa-solid fa-phone"></i>: <%= sale.buyer.phone_number %>
                </div>
              <% end %>
            </td>
            <!-- 購入者の名前、リンク付き -->
            <td>
              <% if sale.buyer.deleted? %>
                Dado de baja
              <% else %>
                <%= link_to sale.buyer.name, user_path(sale.buyer), class: "link-text" %>
              <% end %>
            </td>
            <!-- 提供されたサービスの名前、リンク付き -->
            <td>
              <% if sale.service.deleted? %>
                Eliminado
              <% else %>
                <%= link_to sale.service.title, service_path(sale.service), class: "link-text" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- ページネーション -->
  <%= paginate @sales %>
</div>
</div>