config/routes.rb
Rails.application.routes.draw do
  # ルーティングを登録するファイルです。 ルーティングというのは、ブラウザからRailsアプリへ渡される情報をもとに、登録された動きを行わせるための振り分け設定 

  # ルートページをhomeコントローラのtopアクションに設定
  root "home#top"

  # 静的ページのルート
  get 'static_pages/privacy_policy'
  get 'static_pages/terms_of_service'

  # Deviseユーザー認証関連のルート設定
  # devise_for :usersを通じてユーザーモデルに対する認証ルートを生成
  # controllers オプションを使用して、Deviseのデフォルトのコントローラをカスタムコントローラにオーバーライド。
  # これにより、デフォルトの動作をカスタマイズ。
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'}

  # 特定のユーザーを削除するためのルート
  # match 'users.:id' => 'registrations#destroy'：この部分はregistrations コントローラの destroy アクションにルーティングするための設定。
  # 'users.:id' は、URLにユーザーのIDを含めることを指定しており、このIDをパラメータとしてdestroyアクションに渡します。
  # :via => :delete：これはHTTPメソッドとしてDELETEを指定しています。DELETEメソッドは、RESTful API（分散型システムにおける複数のソフトウェアを連携させるのに適した設計原則の集合、考え方）においてリソースを削除するための標準的な方法。
  # :as => :destroy_user：これは名前付きルートを設定しており、このルートにdestroy_user_pathやdestroy_user_urlといったヘルパーメソッドでアクセスできるようにしています。
  # これにより、ビューやコントローラー内でこのルートを簡単に参照できます。
  match 'users.:id' => 'registrations#destroy', :via => :delete, :as => :destroy_user

  # ユーザー関連のルート、限定的なリソースのみ使用
  # ユーザーリソースの中でeditアクションとshowアクションに対するルートのみを生成する
  resources :users, only: [:edit, :show] do
    # memberブロック内では、特定のユーザーに関連する追加のアクションのルートを定義しています。
    member do
      # get :likes：各ユーザーの「いいね！」リストを表示するためのページへのルート
      get :likes
      # get :orders：ユーザーの注文履歴を表示するためのページへのルートです。
      get :orders
      # get :sales：ユーザーが行った販売の履歴を表示するためのページへのルートです。
      get :sales
    end
  end

  # サービスとレビュー関連のネストされたリソース
  # ユーザーはサービスに対してレビューを投稿したり、既存のレビューを編集することができます。
  # ネストされているため、URLはservices/:service_id/reviews/:idの形式で、サービスIDに基づいてレビューを管理することができます。
  resources :services do
    resources :reviews, only: [:new, :create, :edit, :update]

    # collection doブロック内のpost '/filter', to: 'services#filter'は、servicesリソースに対するカスタムのルートを定義しています。
    # このpostリクエストはservices#filterアクションにマッピングされ、これを使用してサービスを特定の基準でフィルタリングするフォームを処理します。
    collection do
      post '/filter', to: 'services#filter' # サービスをフィルターするアクション
    end
  end

  # いいね機能のルート
  resources :likes, only: [:create, :destroy]

  # 注文関連のルート
  resources :orders do
    # collection doブロック内のget :completedは、注文リソース全体に関連するカスタムアクションを定義
    # 完了した注文の一覧を表示するページに対するルートを提供
    # collectionキーワードは、このアクションが特定の注文のIDに依存しないことを意味する
    # つまり、このルートは/orders/completedの形でアクセスされ、すべての完了した注文を一覧表示するページへと導きます。
    collection do
      get :completed # 完了した注文の表示
    end
    # memberキーワードは、これらのアクションが特定の注文のIDに対して適用されることを意味する
    # URLはそれぞれ/orders/:id/acceptと/orders/:id/rejectの形になります
    # putメソッドは、注文の状態を変更するために使用され、これにより注文の状態が「承認された」または「拒否された」に更新されます。
    member do
      put :accept  # 注文の承認
      put :reject  # 注文の拒否
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- ドキュメントのタイトルとファビコン -->
    <title>Olumeca</title>
    <%= favicon_link_tag 'favicon.jpeg' %>

    <!-- CSRFメタタグと文字エンコーディング -->
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <!-- 言語とビューポートの設定 -->
    <meta http-equiv="Content-Language" content="es">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- スタイルシート -->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!-- JavaScriptの依存関係 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', type: 'module' %>
    
    <!-- スクリプトのプリロード -->
    <link rel="preload" href="http://localhost:3000/assets/es-module-shims.min-606ae9c3279013fe751cee30f719a592f759e705edb66496812f3d9dbce3d850.js" as="script">
    
    <!-- マニフェストへのリンク -->
    <link rel="manifest" href="/path_to_manifest/manifest.json">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-white">
        <div class="container-fluid mt-1 mb-1 ms-3">
          <!-- ナビゲーションロゴ -->
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag 'olumeca.png', alt: 'Olumeca Logo', class: 'logo-dimensions' %>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- サービスへのリンク -->
              <li class="nav-item">
                <%= link_to services_path, class: "nav-link" do %>
                  <i class="fa-solid fa-magnifying-glass"></i> Servicios
                <% end %>
              </li>
              <!-- サービスの新規追加へのリンク -->
              <li class="nav-item">
                <%= link_to new_service_path, class: "nav-link" do %>
                  <i class="fa-solid fa-square-plus"></i> Publicar
                <% end %>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <!-- ユーザーがサインインしている場合のナビゲーション -->
              <% if user_signed_in?  %>
                <li class="nav-item">
                  <%= link_to "https://wa.me/4423831033", class: "nav-link active", aria: { current: "page" } do %>
                    <i class="fab fa-whatsapp me-1"></i>Contactar
                  <% end %>
                </li>
                <!-- ユーザーメニュー -->
                <li class="nav-item dropdown">
                  <%= link_to "Mi Página", "#", class: "nav-link dropdown-toggle", role: "button", data: { bs_toggle: "dropdown" }, aria: { expanded: "false" } %>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li><%= link_to 'Perfil', user_path(current_user), class: "dropdown-item" %></li>
                    <li><%= link_to 'Editar tu cuenta', edit_user_registration_path, class: "dropdown-item" %></li>
                    <li><%= link_to 'Favoritos', likes_user_path(current_user.id), class: "dropdown-item" %></li>
                    <li><%= link_to 'Pedidos realizados', orders_user_path(current_user.id), class: "dropdown-item" %></li>
                    <li><%= link_to 'Pedidos recibidos', sales_user_path(current_user.id), class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= button_to 'Salir', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% else %>
                <!-- ユーザーがサインインしていない場合のナビゲーション -->
                <li class="nav-item">
                  <%= link_to "https://wa.me/4423831033", class: "nav-link active me-3", aria: { current: "page" } do %>
                    <i class="fab fa-whatsapp fa-1x me-1"></i>Contactar
                  <% end %>
                </li>
                <!-- ユーザー登録へのリンク -->
                <li class="nav-item">
                  <%= link_to "Iniciar", new_user_session_path, class: "btn btn-primary me-3 mb-1" %>
                </li>
                <!-- ログインへのリンク -->
                <li class="nav-item">
                  <%= link_to "Registrar", new_user_registration_path, class: "btn btn-success me-2" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <!-- フラッシュメッセージ -->
      <% if flash[:notice] %>
        <div class="alert alert-warning alert-dismissible text-center fade show mb-0 mt-0" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible text-center fade show mb-0 mt-0" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </header>
    <%= yield %>
    <!-- フッター -->
    <footer class="footer bg-white">
      <div class="footer-wrapper">
        <div class="footer-container">
          <p class="footer-item">©Olumeca</p>
        </div>
        <div class="footer-container">
          <!-- リンク -->
          <p class="footer-item"><%= link_to 'Términos y condiciones', static_pages_terms_of_service_path %></p>
          <p class="footer-item"><%= link_to 'Política de privacidad', static_pages_privacy_policy_path %></p>
          <p class="footer-item"><%= link_to 'Perfil Empresa', 'https://miraie-mexico.com/%e4%bc%9a%e7%a4%be%e6%a6%82%e8%a6%81/' %></p>
          <p class="footer-item">
            <!-- SNSアイコン -->
            <%= link_to 'https://www.instagram.com/olumeca/' do %>
              <i class="fab fa-instagram"></i>
            <% end %>
          </p>
          <p class="footer-item">
            <%= link_to 'https://www.facebook.com/profile.php?id=61552368129464' do %>
              <i class="fab fa-facebook-f"></i>
            <% end %>
          </p>
        </div>
      </div>
    </footer>
    <!-- JavaScriptライブラリの読み込み -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <%= javascript_include_tag "main" %>
  </body>
</html>